# Generated by Django 3.1.3 on 2020-11-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CA', 'COMPANY ADMIN'), ('NU', 'NORMAL USER')], default='NU', max_length=2, verbose_name='user role'),
        ),
    ]
