# Generated by Django 3.1.3 on 2020-11-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0002_auto_20201104_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'COMPANY ADMIN'), (2, 'NORMAL USER')], default=2, max_length=2, verbose_name='user role'),
        ),
    ]
