# Generated by Django 3.1.3 on 2020-11-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0002_tours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='Bidamount',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='tours',
            old_name='Listing',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='tours',
            old_name='User',
            new_name='user',
        ),
    ]
