# Generated by Django 3.1.3 on 2020-11-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0003_auto_20201105_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Message',
            field=models.CharField(max_length=150),
        ),
    ]
