# Generated by Django 3.1.3 on 2020-11-06 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0004_auto_20201106_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='AuctionDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='CurrentAmount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='Bidamount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='Listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='estateapp.listing'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
